### ISSUE TITLE
Typo in MSTGTA Plugin

### ISSUE THREAD

**Issue by ca-mtg** [hobu/nitro#8]
TGTEVEL and TGTEVELUNIT

EVEL should be ELEV (for elevation) according to NITF standard.

https://github.com/hobu/nitro/blob/763182ce333f99d9f85fa1449e9cbe16750f72e0/c/nitf/shared/MSTGTA.c#L38

**Comment by hobu** [comment]
This repo is a mirror of https://github.com/mdaus/nitro and the issue should be upstreamed there before making it back down into this repo.

**Comment by ca-mtg** [comment]
Yeah that was my mistake, sorry. I noticed that right after I submitted the issue and saw that it was only number 8. 

This is the issue in the other repo in case someone ends up here by mistake: 
https://github.com/mdaus/nitro/issues/128
